plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.openapi.generator' version '7.11.0'
}

group = 'com.pichincha.dm'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'io.swagger.core.v3:swagger-annotations-jakarta:2.2.31'
	implementation 'jakarta.validation:jakarta.validation-api:3.1.1'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

// OPENAPI_GENERATOR_KIT_START
apply from: "$rootDir/openapi-generator/openapi-generator.gradle"
// OPENAPI_GENERATOR_KIT_END