AYS_MSA_CR_CUSTOMER_OPENAPI_INPUT_SPEC=src/main/resources/openapi.yaml
AYS_MSA_CR_CUSTOMER_OPENAPI_OUTPUT_DIR=build/generated
AYS_MSA_CR_CUSTOMER_OPENAPI_GENERATOR_NAME=spring
AYS_MSA_CR_CUSTOMER_OPENAPI_LIBRARY=spring-boot
AYS_MSA_CR_CUSTOMER_OPENAPI_API_PACKAGE=com.pichincha.dm.cura.customer.infrastructure.entrypoint.controller
AYS_MSA_CR_CUSTOMER_OPENAPI_MODEL_PACKAGE=com.pichincha.dm.cura.customer.infrastructure.entrypoint.controller.entities
AYS_MSA_CR_CUSTOMER_OPENAPI_CONFIG_PACKAGE=com.pichincha.dm.cura.customer.configuration
AYS_MSA_CR_CUSTOMER_OPENAPI_BASE_PACKAGE=com.pichincha.dm.cura.customer
AYS_MSA_CR_CUSTOMER_OPENAPI_SOURCE_FOLDER=src/main/java
AYS_MSA_CR_CUSTOMER_OPENAPI_TASK_NAME=buildSpringServer
AYS_MSA_CR_CUSTOMER_OPENAPI_PLUGIN_VERSION=7.11.0